Update getip

diff --git a/getip b/getip
--- a/getip
+++ b/getip
@@ -344,6 +344,34 @@ chkstatic() {
    return 1
 }
 
+clusterping() {
+   # return 2 if illegal IP format
+   # return 0 if all pings OK
+   # return 1 if at least 1 IP fails in ping
+   ALLOK=0 # yes
+   echo;echo "=== Cluster ping test started at $(date) ==="
+   for i in "$@";do
+      ALLOK=2
+      # echo "A${i}B"
+      [ "$i" = "-c" ] && { ALLOK=2;continue; } 
+      if ! echo "$i" | grep -q -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b";then
+         echo "illegal IP found: $i" 
+         ALLOK=2 # no
+         return $ALLOK
+      fi
+      ping -c 1 "$i" >/dev/null 2>&1
+      PINGRET=$?
+      if [ $PINGRET -ne 0 ];then
+         echo "ping -c 1 $i ===> NOT OK"
+         return 1
+      else
+         echo "ping -c 1 $i ===> ok"
+         ALLOK=0
+      fi
+   done
+   return $ALLOK
+}
+
 isRPI
 
 echo "Hostname is: $(hostname)"
@@ -369,6 +397,21 @@ case "$1" in
         scan_LANside 2 "$GATEWAYIP"
         #arpscan # already tested, but skip
         exit 0;;  
+   -c)  echo
+        echo "Cluster ping. Several hosts will be pinged in sequence..."
+        clusterping $@
+        CRET=$?
+        if [ $CRET -eq 2 ];then
+           echo "$(date): RESULT: FORMAT ERROR: Illegal IP values given."
+           echo "Hint: Please restart with proper IP values like:"
+           echo "example: 'bash $(basename $0) -c \"192.168.0.1 192.168.0.13\"'"
+        elif [ $CRET -eq 1 ];then
+           echo "$(date): RESULT: At least 1 IP ping failed"
+        else
+           echo "$(date): RESULT: Test succeeded, all pings OK"
+        fi
+        exit $CRET
+        ;;
    -a)  echo;getLAN
         echo;echo "start local scan on $(hostname -I|awk '{print $1}')/24...";
         nmap -v -sn $(hostname -I|awk '{print $1}')/24 | sed -e 's/Nmap //g' | grep -B1 -i "up"
@@ -393,7 +436,7 @@ case "$1" in
         # echo "RETCHK=$RETCHK"
         if [ $RETCHK -ne 0 ];then 
            echo "Sorry this function is only valid if you are running Raspian Stretch distro"
-           exit 0
+           exit 1
         else
            chkstatic
         fi
