Update getmac

diff --git a/getmac b/getmac
--- a/getmac
+++ b/getmac
@@ -17,20 +17,24 @@ if [ ! -f $OUIFILE ];then
    exit 1
 fi
 
-sudo arp-scan --retry=6 --ignoredups --localnet > $TMP1
+NOOFSCANS=2
+for num in $(seq 1 $NOOFSCANS);do
+   echo;echo -n " ---- SCAN $num ON MY LAN network ------:";echo
+   sudo arp-scan --retry=6 --ignoredups --localnet > $TMP1
 
-RET=$?
-[ $RET -ne 0 ] && { echo "$(basename $0): ERROR: Can't arp scan. Can't connect to network"; exit 1; }
-while IFS='' read -r line || [[ -n "$line" ]]; do
-    if echo $line | grep -q -E ":.*:.*:.*:";then
-       printf $(echo "$line" | awk '{print $1}')
-       printf "   "
-       MAC=$(echo "$line" | awk '{print $2}')
-       OUI=$(echo ${MAC//[:.- ]/} | tr "[a-f]" "[A-F]" | egrep -o "^[0-9A-F]{6}")
-       OUUT=$(grep "$OUI" $OUIFILE) # wget http://standards.ieee.org/develop/regauth/oui/oui.txt
+   RET=$?
+   [ $RET -ne 0 ] && { echo "$(basename $0): ERROR: Can't arp scan. Can't connect to network"; exit 1; }
+   while IFS='' read -r line || [[ -n "$line" ]]; do
+      if echo $line | grep -q -E ":.*:.*:.*:";then
+          printf $(echo "$line" | awk '{print $1}')
+          printf "   "
+          MAC=$(echo "$line" | awk '{print $2}')
+          OUI=$(echo ${MAC//[:.- ]/} | tr "[a-f]" "[A-F]" | egrep -o "^[0-9A-F]{6}")
+          OUUT=$(grep "$OUI" $OUIFILE) # wget http://standards.ieee.org/develop/regauth/oui/oui.txt
 
-       printf " "
-       grep "$OUUT" $OUIFILE # wget http://standards.ieee.org/develop/regauth/oui/oui.txt
-    fi
-done < "$TMP1"
+          printf " "
+          grep "$OUUT" $OUIFILE # wget http://standards.ieee.org/develop/regauth/oui/oui.txt
+      fi
+   done < "$TMP1"
+done
 [ -f $TMP1 ] && rm -f $TMP  # cleanup
