Update getvendor

diff --git a/getvendor b/getvendor
--- a/getvendor
+++ b/getvendor
@@ -19,7 +19,13 @@ fi
 
 NOOFSCANS=2
 for num in $(seq 1 $NOOFSCANS);do
-   echo;echo -n " ---- SCAN $num ON MY LAN network ------:";echo
+   echo;echo -n " ---- SCAN $num for others on the LAN network ------:";echo
+   if [ ! -f /usr/bin/arp-scan ];then
+      echo "$(basename $0):ERROR: /usr/bin/arp-scan not found"
+      echo "Try '$ sudo apt-get install arp-scan' . Now exit"
+      exit 1
+   fi   
+ 
    sudo arp-scan --retry=6 --ignoredups --localnet > $TMP1
 
    RET=$?
